name: Deploy to laptop

on:
  push:
    branches: [master]

defaults:
  run:
    shell: powershell -ExecutionPolicy Bypass -Command "& '{0}'"
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Fix git safe directory
        run: git config --global --add safe.directory C:/Users/Peter/coderepo/calendar-bot

      - name: Pull latest
        run: |
          git -C C:\Users\Peter\coderepo\calendar-bot fetch origin master
          git -C C:\Users\Peter\coderepo\calendar-bot reset --hard origin/master

      - name: Restart Calendar Bot services
        shell: powershell
        run: Restart-Service -Name "CalendarBotPaper", "CalendarBotTest" -Force
